version: '3.1'

services:
  benchmark:
    container_name: benchmark
    build:
      context: ..
      dockerfile: ./benchmark/Dockerfile
    entrypoint: 'node ./benchmark/index.mjs'
    networks:
      - node-network
    volumes:
      - ..:/usr/src/app
      - /usr/src/app/node_modules
networks:
  node-network:
    driver: bridge
