version: '3.1'

services:
  benchmark:
    container_name: benchmark
    build:
      context: ..
      dockerfile: ./benchmark/Dockerfile
    entrypoint: 'pnpm ts-node ./benchmark/index.ts'
    volumes:
      - ..:/usr/src/app
      - /usr/src/app/node_modules
