name: Benchmark

on:
  push:
  workflow_dispatch:

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run in container
        run: docker-compose -f './benchmark/docker-compose.yml' up
